# Generated by Django 6.0.6 on 2026-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_flights', models.IntegerField(default=0)),
                ('total_flight_hours', models.FloatField(default=0)),
                ('total_distance_km', models.FloatField(default=0)),
                ('active_drones', models.IntegerField(default=0)),
                ('avg_fleet_health', models.FloatField(default=100)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('energy_consumed_wh', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fleet Daily Stats',
                'verbose_name_plural': 'Fleet Daily Stats',
                'ordering': ['-date'],
            },
        ),
    ]
