# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('drones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('survey', 'Survey'), ('inspection', 'Inspection'), ('delivery', 'Delivery'), ('surveillance', 'Surveillance'), ('mapping', 'Mapping'), ('photography', 'Photography'), ('custom', 'Custom')], default='survey', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance_km', models.FloatField(default=0)),
                ('estimated_duration_min', models.FloatField(default=0)),
                ('estimated_battery_usage', models.FloatField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('area_of_operation', models.TextField(blank=True, help_text='Description or GeoJSON of the operational area')),
                ('max_altitude_m', models.FloatField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='drones.drone')),
                ('assigned_pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='accounts.pilot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_m', models.FloatField(default=50)),
                ('speed_ms', models.FloatField(default=10)),
                ('hover_time_s', models.FloatField(default=0)),
                ('action_type', models.CharField(choices=[('flyover', 'Fly Over'), ('hover', 'Hover'), ('take_photo', 'Take Photo'), ('start_video', 'Start Video'), ('stop_video', 'Stop Video'), ('land', 'Land'), ('return_home', 'Return Home')], default='flyover', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'ordering': ['mission', 'sequence_order'],
                'unique_together': {('mission', 'sequence_order')},
            },
        ),
    ]
