# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('battery_low', 'Battery Low'), ('battery_critical', 'Battery Critical'), ('motor_anomaly', 'Motor Anomaly'), ('gps_loss', 'GPS Loss'), ('signal_loss', 'Signal Loss'), ('geofence_breach', 'Geofence Breach'), ('altitude_warning', 'Altitude Warning'), ('speed_warning', 'Speed Warning'), ('temperature_warning', 'Temperature Warning'), ('vibration_warning', 'Vibration Warning'), ('maintenance_due', 'Maintenance Due'), ('system_error', 'System Error'), ('ai_prediction', 'AI Prediction')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='drones.drone')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
