# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_msl', models.FloatField(blank=True, help_text='Altitude above mean sea level (m)', null=True)),
                ('altitude_agl', models.FloatField(blank=True, help_text='Altitude above ground level (m)', null=True)),
                ('ground_speed', models.FloatField(default=0, help_text='Ground speed (m/s)')),
                ('air_speed', models.FloatField(default=0, help_text='Air speed (m/s)')),
                ('vertical_speed', models.FloatField(default=0, help_text='Vertical speed (m/s)')),
                ('heading', models.FloatField(default=0, help_text='Heading in degrees')),
                ('roll', models.FloatField(default=0, help_text='Roll angle in degrees')),
                ('pitch', models.FloatField(default=0, help_text='Pitch angle in degrees')),
                ('yaw', models.FloatField(default=0, help_text='Yaw angle in degrees')),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_current', models.FloatField(blank=True, null=True)),
                ('battery_percentage', models.FloatField(blank=True, null=True)),
                ('battery_temperature', models.FloatField(blank=True, null=True)),
                ('motor_rpm_1', models.FloatField(blank=True, null=True)),
                ('motor_rpm_2', models.FloatField(blank=True, null=True)),
                ('motor_rpm_3', models.FloatField(blank=True, null=True)),
                ('motor_rpm_4', models.FloatField(blank=True, null=True)),
                ('motor_temp_1', models.FloatField(blank=True, null=True)),
                ('motor_temp_2', models.FloatField(blank=True, null=True)),
                ('motor_temp_3', models.FloatField(blank=True, null=True)),
                ('motor_temp_4', models.FloatField(blank=True, null=True)),
                ('vibration_x', models.FloatField(blank=True, null=True)),
                ('vibration_y', models.FloatField(blank=True, null=True)),
                ('vibration_z', models.FloatField(blank=True, null=True)),
                ('gps_satellites', models.IntegerField(blank=True, null=True)),
                ('gps_fix_type', models.IntegerField(blank=True, null=True)),
                ('gps_hdop', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('wind_speed_est', models.FloatField(blank=True, null=True)),
                ('wind_direction_est', models.FloatField(blank=True, null=True)),
                ('ambient_temperature', models.FloatField(blank=True, null=True)),
                ('barometric_pressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Telemetry Data',
                'verbose_name_plural': 'Telemetry Data',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['flight', 'timestamp'], name='idx_telem_flight_ts')],
            },
        ),
    ]
