# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('drones', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('crashed', 'Crashed')], default='planned', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('max_altitude_m', models.FloatField(default=0)),
                ('avg_speed_ms', models.FloatField(default=0)),
                ('max_speed_ms', models.FloatField(default=0)),
                ('energy_consumed_wh', models.FloatField(default=0)),
                ('start_battery_pct', models.FloatField(default=100)),
                ('end_battery_pct', models.FloatField(default=0)),
                ('weather_condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('windy', 'Windy'), ('foggy', 'Foggy'), ('snowy', 'Snowy'), ('stormy', 'Stormy'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('wind_speed_ms', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(default=25)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='drones.drone')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='missions.mission')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='accounts.pilot')),
            ],
            options={
                'verbose_name': 'Flight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_m', models.FloatField(default=0)),
                ('max_altitude_m', models.FloatField(default=0)),
                ('avg_speed_ms', models.FloatField(default=0)),
                ('max_speed_ms', models.FloatField(default=0)),
                ('avg_vertical_speed_ms', models.FloatField(default=0)),
                ('energy_efficiency_m_per_wh', models.FloatField(default=0)),
                ('flight_smoothness_score', models.FloatField(default=100)),
                ('path_efficiency', models.FloatField(default=1.0)),
                ('risk_score', models.FloatField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('battery_consumed_pct', models.FloatField(default=0)),
                ('avg_motor_rpm', models.FloatField(default=0)),
                ('motor_rpm_variance', models.FloatField(default=0)),
                ('avg_vibration', models.FloatField(default=0)),
                ('max_vibration', models.FloatField(default=0)),
                ('gps_accuracy_avg_m', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Flight Analytics',
                'verbose_name_plural': 'Flight Analytics',
                'ordering': ['-computed_at'],
            },
        ),
    ]
