# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(default='DJI', max_length=100)),
                ('drone_type', models.CharField(choices=[('quadcopter', 'Quadcopter'), ('hexacopter', 'Hexacopter'), ('fixed_wing', 'Fixed Wing'), ('vtol', 'VTOL')], default='quadcopter', max_length=20)),
                ('max_altitude_m', models.FloatField(default=120)),
                ('max_speed_ms', models.FloatField(default=20)),
                ('max_flight_time_min', models.IntegerField(default=30)),
                ('weight_kg', models.FloatField(default=1.5)),
                ('payload_capacity_kg', models.FloatField(default=0.5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('retired', 'Retired')], default='active', max_length=20)),
                ('total_flight_hours', models.FloatField(default=0)),
                ('total_flights', models.IntegerField(default=0)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='Unknown', max_length=100)),
                ('chemistry', models.CharField(choices=[('lipo', 'LiPo'), ('li_ion', 'Li-Ion'), ('solid_state', 'Solid State')], default='lipo', max_length=20)),
                ('cells_count', models.IntegerField(default=4)),
                ('design_capacity_mah', models.IntegerField(default=5000)),
                ('current_capacity_mah', models.IntegerField(default=5000)),
                ('voltage_nominal', models.FloatField(default=14.8)),
                ('cycle_count', models.IntegerField(default=0)),
                ('charge_cycles', models.IntegerField(default=0)),
                ('state_of_health', models.FloatField(default=100.0)),
                ('estimated_rul_cycles', models.IntegerField(blank=True, null=True)),
                ('degradation_rate_per_cycle', models.FloatField(default=0.0)),
                ('last_full_charge', models.DateTimeField(blank=True, null=True)),
                ('average_temperature_c', models.FloatField(default=25.0)),
                ('max_temperature_c', models.FloatField(default=25.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery_profile', to='drones.drone')),
            ],
            options={
                'verbose_name': 'Battery Profile',
            },
        ),
        migrations.CreateModel(
            name='ComponentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('motor_1', 'Motor 1'), ('motor_2', 'Motor 2'), ('motor_3', 'Motor 3'), ('motor_4', 'Motor 4'), ('battery', 'Battery'), ('esc', 'ESC'), ('gps', 'GPS'), ('imu', 'IMU'), ('compass', 'Compass'), ('camera', 'Camera'), ('gimbal', 'Gimbal'), ('frame', 'Frame')], max_length=20)),
                ('component_name', models.CharField(max_length=100)),
                ('health_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cycles_count', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('last_inspected', models.DateTimeField(blank=True, null=True)),
                ('predicted_rul_hours', models.FloatField(blank=True, null=True)),
                ('degradation_rate', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('failed', 'Failed')], default='healthy', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='drones.drone')),
            ],
            options={
                'verbose_name': 'Component Health',
                'verbose_name_plural': 'Component Health Records',
                'unique_together': {('drone', 'component_type')},
            },
        ),
    ]
