# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('predictive', 'Predictive'), ('corrective', 'Corrective'), ('emergency', 'Emergency')], default='scheduled', max_length=20)),
                ('component', models.CharField(choices=[('motor_1', 'Motor 1'), ('motor_2', 'Motor 2'), ('motor_3', 'Motor 3'), ('motor_4', 'Motor 4'), ('battery', 'Battery'), ('esc', 'ESC'), ('gps', 'GPS'), ('imu', 'IMU'), ('compass', 'Compass'), ('camera', 'Camera'), ('gimbal', 'Gimbal'), ('frame', 'Frame'), ('full_system', 'Full System')], default='full_system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('predicted_failure_date', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_replaced', models.TextField(blank=True, help_text='Comma-separated list of replaced parts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='drones.drone')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
