from django.db import models


class MLModel(models.Model):
    """Registry of trained machine learning models available for inference."""
    TYPE_CHOICES = [
        ('battery_rul', 'Battery RUL Prediction'),
        ('motor_anomaly', 'Motor Anomaly Detection'),
        ('flight_anomaly', 'Flight Anomaly Detection'),
        ('mission_risk', 'Mission Risk Assessment'),
        ('predictive_maintenance', 'Predictive Maintenance'),
    ]

    name = models.CharField(max_length=200)
    version = models.CharField(max_length=50)
    model_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    description = models.TextField(blank=True)
    file_path = models.CharField(max_length=500, blank=True)
    accuracy = models.FloatField(null=True, blank=True)
    f1_score = models.FloatField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    trained_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['name', 'version']
        ordering = ['-created_at']
        verbose_name = 'ML Model'

    def __str__(self):
        return f"{self.name} v{self.version} ({'active' if self.is_active else 'inactive'})"


class MLPrediction(models.Model):
    """Individual prediction record generated by an ML model."""
    TYPE_CHOICES = [
        ('battery_rul', 'Battery RUL'),
        ('motor_anomaly', 'Motor Anomaly'),
        ('flight_anomaly', 'Flight Anomaly'),
        ('mission_risk', 'Mission Risk'),
        ('predictive_maintenance', 'Predictive Maintenance'),
    ]

    drone = models.ForeignKey(
        'drones.Drone', related_name='predictions', on_delete=models.CASCADE,
    )
    flight = models.ForeignKey(
        'flights.Flight', related_name='predictions',
        on_delete=models.SET_NULL, null=True, blank=True,
    )
    model = models.ForeignKey(
        MLModel, related_name='predictions',
        on_delete=models.SET_NULL, null=True, blank=True,
    )
    prediction_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    input_summary = models.JSONField(default=dict, blank=True)
    prediction_value = models.FloatField(default=0)
    prediction_label = models.CharField(max_length=100, blank=True)
    confidence_score = models.FloatField(default=0)
    explanation = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'ML Prediction'

    def __str__(self):
        return f"{self.get_prediction_type_display()} - {self.drone.name} ({self.confidence_score:.0%})"
