# Generated by Django 6.0.6 on 2026-06-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('battery_rul', 'Battery RUL Prediction'), ('motor_anomaly', 'Motor Anomaly Detection'), ('flight_anomaly', 'Flight Anomaly Detection'), ('mission_risk', 'Mission Risk Assessment'), ('predictive_maintenance', 'Predictive Maintenance')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('battery_rul', 'Battery RUL'), ('motor_anomaly', 'Motor Anomaly'), ('flight_anomaly', 'Flight Anomaly'), ('mission_risk', 'Mission Risk'), ('predictive_maintenance', 'Predictive Maintenance')], max_length=30)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('prediction_value', models.FloatField(default=0)),
                ('prediction_label', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='drones.drone')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='flights.flight')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ml.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'ordering': ['-created_at'],
            },
        ),
    ]
